### ISSUE TITLE
Port not compatible with OnePlus 8t T-Mobile kb2007

### ISSUE THREAD

**Issue by Aizazkhan666** [toraidl/coloros_port_kebab#1]
New ColorOS 15 port doesn't boot in kb2007 model of OnePlus 8t. I successfully flashed kb2000 coloros 14 stock package. Then used adb sideload in orangefox but it goes straight to fastboot. System doesn't boot. Please release a fix
It works fine on every other variant of OnePlus 8t

**Comment by toraidl** [comment]
It should be fixed by flahsing stock dtbo.img and boot.img
